// Code generated by 'yaegi extract github.com/knadh/koanf/providers/file'. DO NOT EDIT.

package imports

import (
	"github.com/knadh/koanf/providers/file"
	"reflect"
)

func init() {
	Symbols["github.com/knadh/koanf/providers/file/file"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Provider": reflect.ValueOf(file.Provider),

		// type definitions
		"File": reflect.ValueOf((*file.File)(nil)),
	}
}
