// Code generated by 'yaegi extract github.com/knadh/koanf/parsers/json'. DO NOT EDIT.

package imports

import (
	"github.com/knadh/koanf/parsers/json"
	"reflect"
)

func init() {
	Symbols["github.com/knadh/koanf/parsers/json/json"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Parser": reflect.ValueOf(json.Parser),

		// type definitions
		"JSON": reflect.ValueOf((*json.JSON)(nil)),
	}
}
