// Code generated by 'yaegi extract github.com/knadh/koanf/parsers/yaml'. DO NOT EDIT.

package imports

import (
	"github.com/knadh/koanf/parsers/yaml"
	"reflect"
)

func init() {
	Symbols["github.com/knadh/koanf/parsers/yaml/yaml"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Parser": reflect.ValueOf(yaml.Parser),

		// type definitions
		"YAML": reflect.ValueOf((*yaml.YAML)(nil)),
	}
}
