// Code generated by 'yaegi extract github.com/knadh/koanf/providers/env'. DO NOT EDIT.

package imports

import (
	"github.com/knadh/koanf/providers/env"
	"reflect"
)

func init() {
	Symbols["github.com/knadh/koanf/providers/env/env"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Provider":          reflect.ValueOf(env.Provider),
		"ProviderWithValue": reflect.ValueOf(env.ProviderWithValue),

		// type definitions
		"Env": reflect.ValueOf((*env.Env)(nil)),
	}
}
